const URL_FETCH_CUSTOMER_LIST = '/customer';
const URL_FETCH_CUSTOMER_DETAIL = '/customer';
const URL_FETCH_CUSTOMER_LESSON_LIST = '/customer/lesson';
const URL_FETCH_CUSTOMER_LESSON_HISTORY = '/customer/lessonHistory'
const URL_SEARCH_CUSTOMER_LIST_BY_KEYWORD = '/customer/search';
const URL_DELETE_CUSTOMER = '/customer';

export {
  URL_FETCH_CUSTOMER_LIST,
  URL_FETCH_CUSTOMER_DETAIL,
  URL_FETCH_CUSTOMER_LESSON_LIST,
  URL_FETCH_CUSTOMER_LESSON_HISTORY,
  URL_SEARCH_CUSTOMER_LIST_BY_KEYWORD,
  URL_DELETE_CUSTOMER,
};
