const URL_FETCH_CUSTOMER_LIST = '/customer';
const URL_FETCH_CUSTOMER_DETAIL = '/customer';
const URL_FETCH_CUSTOMER_LESSON_LIST = '/customer/lesson';
const URL_SEARCH_CUSTOMER_LIST_BY_KEYWORD = '/customer/search';

export {
  URL_FETCH_CUSTOMER_LIST,
  URL_FETCH_CUSTOMER_DETAIL,
  URL_FETCH_CUSTOMER_LESSON_LIST,
  URL_SEARCH_CUSTOMER_LIST_BY_KEYWORD,
};
