const URL_FETCH_COACH_LIST = '/coach';
const URL_FETCH_COACH_LESSON_LIST = '/coach/lesson';
const URL_DELETE_COACH = '/coach';

export { URL_FETCH_COACH_LIST, URL_FETCH_COACH_LESSON_LIST, URL_DELETE_COACH };
