const URL_SCHEDULE_LESSON_BY_DATE = `/calendar/schedule`;
const URL_SCHEDULE_LESSON_BY_PERIOD = `/calendar/schedule-period`;
const URL_CREATE_SCHEDULE_LESSON = `/calendar`;

export {
  URL_SCHEDULE_LESSON_BY_DATE,
  URL_SCHEDULE_LESSON_BY_PERIOD,
  URL_CREATE_SCHEDULE_LESSON,
};
