const URL_SCHEDULE_LESSON_BY_DATE = '/calendar/schedule';
const URL_SCHEDULE_LESSON_BY_PERIOD = '/calendar/schedule-period';
const URL_CREATE_SCHEDULE_LESSON = '/calendar';
const URL_CREATE_CHANGE_SCHEDULE_LESSON = '/calendar/change';
const URL_UPDATE_SCHEDULE_LESSON = '/calendar/update';
const URL_DELETE_SCHEDULE_LESSON = '/calendar/delete';
const URL_IS_DUPLICATE_CHECK_SCHEDULE_LESSON = '/calendar/check';

export {
  URL_SCHEDULE_LESSON_BY_DATE,
  URL_SCHEDULE_LESSON_BY_PERIOD,
  URL_CREATE_SCHEDULE_LESSON,
  URL_CREATE_CHANGE_SCHEDULE_LESSON,
  URL_UPDATE_SCHEDULE_LESSON,
  URL_DELETE_SCHEDULE_LESSON,
  URL_IS_DUPLICATE_CHECK_SCHEDULE_LESSON,
};
