import AppLayout from "@components/layout/AppLayout";
import { globalStyles } from "@styles/styles";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {globalStyles}
      <AppLayout>
        <Component {...pageProps} />
      </AppLayout>
      <div id="portal" />
    </>
  );
}
