import { useState } from 'react';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import {
  QueryClient,
  QueryClientProvider,
  Hydrate,
} from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
// import { globalStyles } from '@styles/styles';
import { config } from '@lib/react-query/config';
import { RecoilRoot } from 'recoil';
import ModalProvider from 'src/provider/ModalProvider';
import AppLayout from '@components/layout/AppLayout';

export default function App({ Component, pageProps }: AppProps) {
  const [queryClient] = useState(() => new QueryClient(config));

  return (
    <RecoilRoot>
      <Head>
        <title>테니스 픽</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <ReactQueryDevtools initialIsOpen={true} />
        <Hydrate state={pageProps?.dehydrateState}>
          {/* {globalStyles} */}
          <AppLayout>
            <Component {...pageProps} />
          </AppLayout>
          <div id="portal" />
          <div id="layerPortal" />
          <div id="confirmModal" />
          <div id="drawer" />
          <ModalProvider />
        </Hydrate>
      </QueryClientProvider>
    </RecoilRoot>
  );
}
