export type AdminInfo = {
  account: string;
  address: string;
  business_end_hours: number;
  business_hours: number;
  business_number: string;
  // business_type: 'individual';
  business_type: string;
  center_id: number;
  contact_number: string;
  email: string;
  exp: number;
  iat: number;
  id: number;
  individualSales: number;
  individualSalesOption: string;
  insuranceOption: string;
  lesson_setting_time: number;
  name: string;
  owner_name: string;
  password: string;
  phone: string;
  role: string;
  salary: number;
  salaryOption: string;
  settlementRate: number;
  settlementRateOption: string;
  totalSales: number;
  totalSalesOption: string;
  vatOption: string;
};
